### ISSUE TITLE
Change the maximum number of steps for one eposide 

### ISSUE THREAD

**Issue by jiafei1224** [TheMTank/ai2thor-experiments#13]
Hi there, i try to change the max_step_num for rainbow  algorithms under the main.py, however it doesn't seem to work. Can advise me please? Thank you

**Comment by beduffy** [comment]
Check examples/random_walk.py. If you change:
`config_dict = {'max_episode_length': 2000}` to 100 the episode length will have 100 steps before resetting. That's what the title of your question asked.

As for the body of your question, in the rainbow code, the arg for `--max-num-steps` (not `max_step_num`) is for the number of training steps, not episode length and it's default is set to 500,000. That means the algorithm trains for 500,000 steps and is not much to do with episodes. Hopefully that clears it up. 

If you would like to change the episode length for rainbow change the rainbow config file and use the param for `max_episode_length`
