### ISSUE TITLE
How to train on server?

### ISSUE THREAD

**Issue by jiafei1224** [TheMTank/ai2thor-experiments#14]
I would like to train the rainbow main.py on a remote server without a GUI?

**Comment by beduffy** [comment]
One of our colleagues wrote this, check it out.
https://medium.com/@etendue2013/how-to-run-ai2-thor-simulation-fast-with-google-cloud-platform-gcp-c9fcde213a4a

**Comment by jiafei1224** [comment]
Is there any other ways to improve training speed for ai2thor wrapper with rainbow algorithms?
