### ISSUE TITLE
Calling different tasks for different iteration

### ISSUE THREAD

**Issue by zyzhang1130** [TheMTank/ai2thor-experiments#16]
Hi,
May I check if it is possible to define multiple tasks in tasks.py and call just one of them based on certain condition. If it is possible, how to do it ?
My guess is to modify rainbow_example.json script with a if-condition (I am using the rainbow algorithm to train the model). But since the task in that script is defined with a cell I'm not sure how exactly to implement that.

Thank you very much.

**Comment by beduffy** [comment]
You will have to create a task with the same interface as `PickUpTask` in tasks.py and in the config dict/file which get's passed to 
`env = AI2ThorEnv(config_dict=config_dict)`
will have to include:
```
'task': {
            'task_name': 'PickUpTask',
            'target_objects': {'Mug': 1, 'Bowl': 5}
        }
```

For different tasks in different episodes you will probably have to create a new environment.

**Comment by zyzhang1130** [comment]
I tried to define a new config_dict immediately after 
state, done = env.reset(), False (line 157, rainbow main.py)
(inside the if logic) and load it by 
env = AI2ThorEnv(config_dict=config_dict)

and it threw me error at line
           next_state, reward, done, _ = env.step(action)  # Step  (line 162)
saying:
AttributeError: 'NoneType' object has no attribute 'metadata'


May I know what's wrong with my modification? Thank you so much.
