### ISSUE TITLE
How long does it take to train rainbow

### ISSUE THREAD

**Issue by snow2white** [TheMTank/ai2thor-experiments#28]
Roughly how long it took you to train Rainbow

**Comment by beduffy** [comment]
Hello, thanks for your question. We haven't worked on this repo for a long time and this is using quite an old version of ai2thor, the environment has improved a lot since then. But roughly from memory, it took a night but started seeing some reasonable results after a few hours

**Comment by snow2white** [comment]
Hi, Thanks for your answer. May I ask about your hardware.

**Comment by beduffy** [comment]
@fgtoralesch kindly provided the specs of his desktop when he trained this:

```
CPU:
Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz
GPU:
product: GP104 [GeForce GTX 1080]
vendor: NVIDIA Corporation
```
but he thinks a normal laptop could do it overnight as well.
